name: CI/CD Pipeline to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20.15.1'

    - name: Install Vue.js dependencies
      run: npm install --legacy-peer-deps
    - name: Grant execute permission to vite
      run: chmod +x ./node_modules/.bin/vite

    - name: Build Vue.js application
      run: npm run build

    - name: Deploy to EC2
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          # Remove existing files in the web directory
          sudo rm -rf /opt/bitnami/apache/htdocs/*
          
          # Copy the built Vue.js files to the web directory
          sudo cp -r ${{ github.workspace }}/dist/* /opt/bitnami/apache/htdocs/
          
          # Set proper permissions
          sudo chown -R bitnami:bitnami /opt/bitnami/apache/htdocs
          
          # Restart Apache to apply changes
          sudo /opt/bitnami/ctlscript.sh restart apache
